//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CM_RGB.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int LBL_SPEED {
            get {
                return ((int)(this["LBL_SPEED"]));
            }
            set {
                this["LBL_SPEED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LBL_COLORMODE {
            get {
                return ((bool)(this["LBL_COLORMODE"]));
            }
            set {
                this["LBL_COLORMODE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color LBL_COLOR1 {
            get {
                return ((global::System.Drawing.Color)(this["LBL_COLOR1"]));
            }
            set {
                this["LBL_COLOR1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lime")]
        public global::System.Drawing.Color LBL_COLOR2 {
            get {
                return ((global::System.Drawing.Color)(this["LBL_COLOR2"]));
            }
            set {
                this["LBL_COLOR2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LBL_DIRECTION {
            get {
                return ((bool)(this["LBL_DIRECTION"]));
            }
            set {
                this["LBL_DIRECTION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int ALTL_SPEED {
            get {
                return ((int)(this["ALTL_SPEED"]));
            }
            set {
                this["ALTL_SPEED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ALTL_COLORMODE {
            get {
                return ((bool)(this["ALTL_COLORMODE"]));
            }
            set {
                this["ALTL_COLORMODE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color ALTL_COLOR1 {
            get {
                return ((global::System.Drawing.Color)(this["ALTL_COLOR1"]));
            }
            set {
                this["ALTL_COLOR1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lime")]
        public global::System.Drawing.Color ALTL_COLOR2 {
            get {
                return ((global::System.Drawing.Color)(this["ALTL_COLOR2"]));
            }
            set {
                this["ALTL_COLOR2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ALTL_DIRECTION {
            get {
                return ((bool)(this["ALTL_DIRECTION"]));
            }
            set {
                this["ALTL_DIRECTION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int SLBL_SPEED {
            get {
                return ((int)(this["SLBL_SPEED"]));
            }
            set {
                this["SLBL_SPEED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SLBL_COLORMODE {
            get {
                return ((bool)(this["SLBL_COLORMODE"]));
            }
            set {
                this["SLBL_COLORMODE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color SLBL_COLOR1 {
            get {
                return ((global::System.Drawing.Color)(this["SLBL_COLOR1"]));
            }
            set {
                this["SLBL_COLOR1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lime")]
        public global::System.Drawing.Color SLBL_COLOR2 {
            get {
                return ((global::System.Drawing.Color)(this["SLBL_COLOR2"]));
            }
            set {
                this["SLBL_COLOR2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SLBL_DIRECTION {
            get {
                return ((bool)(this["SLBL_DIRECTION"]));
            }
            set {
                this["SLBL_DIRECTION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int SPRL_SPEED {
            get {
                return ((int)(this["SPRL_SPEED"]));
            }
            set {
                this["SPRL_SPEED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SPRL_COLORMODE {
            get {
                return ((bool)(this["SPRL_COLORMODE"]));
            }
            set {
                this["SPRL_COLORMODE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color SPRL_COLOR1 {
            get {
                return ((global::System.Drawing.Color)(this["SPRL_COLOR1"]));
            }
            set {
                this["SPRL_COLOR1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lime")]
        public global::System.Drawing.Color SPRL_COLOR2 {
            get {
                return ((global::System.Drawing.Color)(this["SPRL_COLOR2"]));
            }
            set {
                this["SPRL_COLOR2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SPRL_DIRECTION {
            get {
                return ((bool)(this["SPRL_DIRECTION"]));
            }
            set {
                this["SPRL_DIRECTION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int WIPE_SPEED {
            get {
                return ((int)(this["WIPE_SPEED"]));
            }
            set {
                this["WIPE_SPEED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WIPE_COLORMODE {
            get {
                return ((bool)(this["WIPE_COLORMODE"]));
            }
            set {
                this["WIPE_COLORMODE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color WIPE_COLOR1 {
            get {
                return ((global::System.Drawing.Color)(this["WIPE_COLOR1"]));
            }
            set {
                this["WIPE_COLOR1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lime")]
        public global::System.Drawing.Color WIPE_COLOR2 {
            get {
                return ((global::System.Drawing.Color)(this["WIPE_COLOR2"]));
            }
            set {
                this["WIPE_COLOR2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WIPE_DIRECTION {
            get {
                return ((bool)(this["WIPE_DIRECTION"]));
            }
            set {
                this["WIPE_DIRECTION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int BRTH_SPEED {
            get {
                return ((int)(this["BRTH_SPEED"]));
            }
            set {
                this["BRTH_SPEED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BRTH_COLORMODE {
            get {
                return ((bool)(this["BRTH_COLORMODE"]));
            }
            set {
                this["BRTH_COLORMODE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color BRTH_COLOR1 {
            get {
                return ((global::System.Drawing.Color)(this["BRTH_COLOR1"]));
            }
            set {
                this["BRTH_COLOR1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lime")]
        public global::System.Drawing.Color BRTH_COLOR2 {
            get {
                return ((global::System.Drawing.Color)(this["BRTH_COLOR2"]));
            }
            set {
                this["BRTH_COLOR2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BRTH_DIRECTION {
            get {
                return ((bool)(this["BRTH_DIRECTION"]));
            }
            set {
                this["BRTH_DIRECTION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int RAND_SPEED {
            get {
                return ((int)(this["RAND_SPEED"]));
            }
            set {
                this["RAND_SPEED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RAND_COLORMODE {
            get {
                return ((bool)(this["RAND_COLORMODE"]));
            }
            set {
                this["RAND_COLORMODE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color RAND_COLOR1 {
            get {
                return ((global::System.Drawing.Color)(this["RAND_COLOR1"]));
            }
            set {
                this["RAND_COLOR1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lime")]
        public global::System.Drawing.Color RAND_COLOR2 {
            get {
                return ((global::System.Drawing.Color)(this["RAND_COLOR2"]));
            }
            set {
                this["RAND_COLOR2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RAND_DIRECTION {
            get {
                return ((bool)(this["RAND_DIRECTION"]));
            }
            set {
                this["RAND_DIRECTION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int RLINE_SPEED {
            get {
                return ((int)(this["RLINE_SPEED"]));
            }
            set {
                this["RLINE_SPEED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RLINE_COLORMODE {
            get {
                return ((bool)(this["RLINE_COLORMODE"]));
            }
            set {
                this["RLINE_COLORMODE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color RLINE_COLOR1 {
            get {
                return ((global::System.Drawing.Color)(this["RLINE_COLOR1"]));
            }
            set {
                this["RLINE_COLOR1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lime")]
        public global::System.Drawing.Color RLINE_COLOR2 {
            get {
                return ((global::System.Drawing.Color)(this["RLINE_COLOR2"]));
            }
            set {
                this["RLINE_COLOR2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RLINE_DIRECTION {
            get {
                return ((bool)(this["RLINE_DIRECTION"]));
            }
            set {
                this["RLINE_DIRECTION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int RSQR_SPEED {
            get {
                return ((int)(this["RSQR_SPEED"]));
            }
            set {
                this["RSQR_SPEED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RSQR_COLORMODE {
            get {
                return ((bool)(this["RSQR_COLORMODE"]));
            }
            set {
                this["RSQR_COLORMODE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color RSQR_COLOR1 {
            get {
                return ((global::System.Drawing.Color)(this["RSQR_COLOR1"]));
            }
            set {
                this["RSQR_COLOR1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lime")]
        public global::System.Drawing.Color RSQR_COLOR2 {
            get {
                return ((global::System.Drawing.Color)(this["RSQR_COLOR2"]));
            }
            set {
                this["RSQR_COLOR2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RSQR_DIRECTION {
            get {
                return ((bool)(this["RSQR_DIRECTION"]));
            }
            set {
                this["RSQR_DIRECTION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int RPATH_SPEED {
            get {
                return ((int)(this["RPATH_SPEED"]));
            }
            set {
                this["RPATH_SPEED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RPATH_COLORMODE {
            get {
                return ((bool)(this["RPATH_COLORMODE"]));
            }
            set {
                this["RPATH_COLORMODE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color RPATH_COLOR1 {
            get {
                return ((global::System.Drawing.Color)(this["RPATH_COLOR1"]));
            }
            set {
                this["RPATH_COLOR1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lime")]
        public global::System.Drawing.Color RPATH_COLOR2 {
            get {
                return ((global::System.Drawing.Color)(this["RPATH_COLOR2"]));
            }
            set {
                this["RPATH_COLOR2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RPATH_DIRECTION {
            get {
                return ((bool)(this["RPATH_DIRECTION"]));
            }
            set {
                this["RPATH_DIRECTION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int BALL_SPEED {
            get {
                return ((int)(this["BALL_SPEED"]));
            }
            set {
                this["BALL_SPEED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BALL_COLORMODE {
            get {
                return ((bool)(this["BALL_COLORMODE"]));
            }
            set {
                this["BALL_COLORMODE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color BALL_COLOR1 {
            get {
                return ((global::System.Drawing.Color)(this["BALL_COLOR1"]));
            }
            set {
                this["BALL_COLOR1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lime")]
        public global::System.Drawing.Color BALL_COLOR2 {
            get {
                return ((global::System.Drawing.Color)(this["BALL_COLOR2"]));
            }
            set {
                this["BALL_COLOR2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BALL_DIRECTION {
            get {
                return ((bool)(this["BALL_DIRECTION"]));
            }
            set {
                this["BALL_DIRECTION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int CCYCL_SPEED {
            get {
                return ((int)(this["CCYCL_SPEED"]));
            }
            set {
                this["CCYCL_SPEED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CCYCL_COLORMODE {
            get {
                return ((bool)(this["CCYCL_COLORMODE"]));
            }
            set {
                this["CCYCL_COLORMODE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color CCYCL_COLOR1 {
            get {
                return ((global::System.Drawing.Color)(this["CCYCL_COLOR1"]));
            }
            set {
                this["CCYCL_COLOR1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lime")]
        public global::System.Drawing.Color CCYCL_COLOR2 {
            get {
                return ((global::System.Drawing.Color)(this["CCYCL_COLOR2"]));
            }
            set {
                this["CCYCL_COLOR2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CCYCL_DIRECTION {
            get {
                return ((bool)(this["CCYCL_DIRECTION"]));
            }
            set {
                this["CCYCL_DIRECTION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int VRAIN_SPEED {
            get {
                return ((int)(this["VRAIN_SPEED"]));
            }
            set {
                this["VRAIN_SPEED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool VRAIN_COLORMODE {
            get {
                return ((bool)(this["VRAIN_COLORMODE"]));
            }
            set {
                this["VRAIN_COLORMODE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color VRAIN_COLOR1 {
            get {
                return ((global::System.Drawing.Color)(this["VRAIN_COLOR1"]));
            }
            set {
                this["VRAIN_COLOR1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lime")]
        public global::System.Drawing.Color VRAIN_COLOR2 {
            get {
                return ((global::System.Drawing.Color)(this["VRAIN_COLOR2"]));
            }
            set {
                this["VRAIN_COLOR2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool VRAIN_DIRECTION {
            get {
                return ((bool)(this["VRAIN_DIRECTION"]));
            }
            set {
                this["VRAIN_DIRECTION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int HRAIN_SPEED {
            get {
                return ((int)(this["HRAIN_SPEED"]));
            }
            set {
                this["HRAIN_SPEED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HRAIN_COLORMODE {
            get {
                return ((bool)(this["HRAIN_COLORMODE"]));
            }
            set {
                this["HRAIN_COLORMODE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color HRAIN_COLOR1 {
            get {
                return ((global::System.Drawing.Color)(this["HRAIN_COLOR1"]));
            }
            set {
                this["HRAIN_COLOR1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lime")]
        public global::System.Drawing.Color HRAIN_COLOR2 {
            get {
                return ((global::System.Drawing.Color)(this["HRAIN_COLOR2"]));
            }
            set {
                this["HRAIN_COLOR2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HRAIN_DIRECTION {
            get {
                return ((bool)(this["HRAIN_DIRECTION"]));
            }
            set {
                this["HRAIN_DIRECTION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int KEYP_SPEED {
            get {
                return ((int)(this["KEYP_SPEED"]));
            }
            set {
                this["KEYP_SPEED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool KEYP_COLORMODE {
            get {
                return ((bool)(this["KEYP_COLORMODE"]));
            }
            set {
                this["KEYP_COLORMODE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color KEYP_COLOR1 {
            get {
                return ((global::System.Drawing.Color)(this["KEYP_COLOR1"]));
            }
            set {
                this["KEYP_COLOR1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lime")]
        public global::System.Drawing.Color KEYP_COLOR2 {
            get {
                return ((global::System.Drawing.Color)(this["KEYP_COLOR2"]));
            }
            set {
                this["KEYP_COLOR2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool KEYP_DIRECTION {
            get {
                return ((bool)(this["KEYP_DIRECTION"]));
            }
            set {
                this["KEYP_DIRECTION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TRAIL")]
        public string LOCKEFFECT {
            get {
                return ((string)(this["LOCKEFFECT"]));
            }
            set {
                this["LOCKEFFECT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int TRAIL_SPEED {
            get {
                return ((int)(this["TRAIL_SPEED"]));
            }
            set {
                this["TRAIL_SPEED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color TRAIL_COLOR1 {
            get {
                return ((global::System.Drawing.Color)(this["TRAIL_COLOR1"]));
            }
            set {
                this["TRAIL_COLOR1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lime")]
        public global::System.Drawing.Color TRAIL_COLOR2 {
            get {
                return ((global::System.Drawing.Color)(this["TRAIL_COLOR2"]));
            }
            set {
                this["TRAIL_COLOR2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TRAIL_COLORMODE {
            get {
                return ((bool)(this["TRAIL_COLORMODE"]));
            }
            set {
                this["TRAIL_COLORMODE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TRAIL_DIRECTION {
            get {
                return ((bool)(this["TRAIL_DIRECTION"]));
            }
            set {
                this["TRAIL_DIRECTION"] = value;
            }
        }
    }
}
